### ISSUE TITLE
Why all callbacks are called before next write is issued?

### ISSUE THREAD

**Issue by mcheshkov** [typicode/steno#11]
1. Issue a write
2. It will put callback in `callbacks`
3. Write hit disc, we are waiting for `fs.writeFile` to complete
4. Issue another write
5. It will put another callback to `callbacks`
6. First write completed, rename completed
7. Now we calling all callbacks, but only first one should be called

Situation gets worse when you issue multiple writes after stuck one - there will never be any write for that call, so it's not clear when callback should be called. I think it should when his write or first one after is completed. Could be implemented with two lists of callbacks, one for current write, and one for next.

**Comment by typicode** [comment]
You're right, thanks a lot for noticing it!
I've added a second list of callbacks. I think it should be ok now. If you want to double check and I'll publish it.

**Comment by typicode** [comment]
Released in `v0.4.4`
