### ISSUE TITLE
tsconfig: exported as commonjs module

### ISSUE THREAD

**Issue by edwindj** [typicode/steno#19]
Thanks for your wonderful packages! 

I ran into an issue with steno, using vite / svelte, namely that steno is exported as a commonjs module.
My issue is fixed when I add 

```
"module": "ES2020",
```
to "tsconfig.json". 

(Not sure if you intended to export steno.js as commonjs)

Best,

Edwin

**Comment by typicode** [comment]
Thanks :)
I've just published a new version. Steno is now a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
