### ISSUE TITLE
Steno on Deno

### ISSUE THREAD

**Issue by Bellisario** [typicode/steno#26]
This is just an announcement (discussions are not enabled in this repo :disappointed:) for who would like to use Steno on Deno :sauropod:.

Just to try, I decided to "transform" :gear: Steno into a Deno version (whose I called Sdeno :open_mouth:).
I published it on GitHub :peace_symbol: and on Deno Packages :package:!
Feel free to contribute!!! :wink:

---
Here are all the links :link::
https://github.com/Bellisario/sdeno
https://deno.land/x/sdeno

**Comment by typicode** [comment]
Thanks for sharing :)
